# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Puffin < Formula
  desc "A beautiful and simple terminal dashboard for hledger"
  homepage "https://github.com/siddhantac/puffin/"
  version "2.1.5"

  depends_on "hledger"

  on_macos do
    on_intel do
      url "https://github.com/siddhantac/puffin/releases/download/v2.1.5/puffin_2.1.5_Darwin_x86_64.tar.gz"
      sha256 "b09e5884764ed8709d62532ce9f134fc71175241897aead224a31a2fb220f5b5"

      def install
        bin.install "puffin"
      end
    end
    on_arm do
      url "https://github.com/siddhantac/puffin/releases/download/v2.1.5/puffin_2.1.5_Darwin_arm64.tar.gz"
      sha256 "9869eb1390594d368b7b4fe65dc5cf7f0dc42022301903e9f0aec43b6a4d56c4"

      def install
        bin.install "puffin"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/siddhantac/puffin/releases/download/v2.1.5/puffin_2.1.5_Linux_x86_64.tar.gz"
        sha256 "3c84692d9fc360004f4cc969eee0c4c8a8d9c8e035e271d9a2b150fa30e9b9c8"

        def install
          bin.install "puffin"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/siddhantac/puffin/releases/download/v2.1.5/puffin_2.1.5_Linux_arm64.tar.gz"
        sha256 "a77b5ee0684cffbc053126e17ee7e06846bd394931a42d3d5e1ce228db1e8d38"

        def install
          bin.install "puffin"
        end
      end
    end
  end
end
